### ISSUE TITLE
Tooltip incompatibility with TradeSkillMaster

### ISSUE THREAD

**Issue by jungheeMW** [MMOSimca/BattlePetBreedID#13]
Tooltip for BPBID overlaps with TradeSkillMaster's tooltip. The screenshot attached is using default settings for BPBID.
BPBID version: 1.29.0
TSM version: 4.14.5
<img width="233" alt="battlepet breed ID incompatible with TSM" src="https://github.com/user-attachments/assets/e33e7a0a-0567-4d3f-912b-270e7ef2e287">

**Comment by swotam** [comment]
Experiencing the same issue here, also with TSM installed. Would it be possible to integrate the BPBID tooltip into into the existing tooltip as opposed to having it in a separate one?

**Comment by MMOSimca** [comment]
@swotam that would be really tricky because of the way TSM draws its tooltips. I did figure out the issue with this and fixed it in c26ac56b.

The solution isn't perfect - for some reason for like 5 seconds after reloading UI, pet items don't have a tooltip at all. But that's a really minor issue and most people aren't spamming reload UI, so I think it's fine.

**Comment by zeenk** [comment]
> Would it be possible to integrate the BPBID tooltip into into the existing tooltip as opposed to having it in a separate one?

Maybe if you use this Lib that the Auctionator dev created? https://github.com/plusmouse/LibBattlePetTooltipLine
As you can see the auction tooltip info from Auctionator is on the main tooltip without having to make extra tooltip

![2024-08-16_22-43-31](https://github.com/user-attachments/assets/6d572eed-04f4-4a23-8cb5-8be15563b8ee)

**Comment by swotam** [comment]
@MMOSimca new tooltip looks good. I like the suggestion @zeenk posted as well if that's easily done.
