### ISSUE TITLE
Breeds not showing correctly in pet journal

### ISSUE THREAD

**Issue by octavius-dev** [MMOSimca/BattlePetBreedID#20]
Addon version name: 11.0.5
Client build: Retail 110005

Breeds aren't showing correctly. I have three "Faceless Minion" that aren't showing the build correctly.  So I have a P/P, P/S and a ???.

I checked the addon "Pet Tracker" and this also has the breeds wrong for these three pets, they have them as P/P, H/B and a H/B.

![image](https://github.com/user-attachments/assets/37996fd3-55fd-4e3f-8942-6adcc8a85f82)
![image](https://github.com/user-attachments/assets/5cfd9e6c-0740-4782-ae54-893ca67190e9)
![image](https://github.com/user-attachments/assets/0b6dfd9b-74c6-4dee-977b-0a30917c8fc3)
![image](https://github.com/user-attachments/assets/2d6a0e1d-020c-4582-b2d6-df9567c18b76)

**Comment by MMOSimca** [comment]
What's wrong about this?

From what I can see, this information appears to be correct.

The ??? one is EITHER H/S or H/B, but the addon cannot tell because the stats at level 1 for H/S and H/B are identical. To 'fix' that one, level it up to level 2 or higher.

**Comment by octavius-dev** [comment]
**Pet 1: Faceless Minion**
Health: 152
Power: 13
Speed: 10

**Pet 2: Faceless Minion**
Health: 152
Power: 12
Speed: 11

**Pet 3: Faceless Minion**
Health: 152
Power: 11
Speed: 11

For the above three pets I get the following from the mentioned addons:-

Battle Pet Breed ID: P/P, P/S, ???
PetTracker: P/P, H/B, H/B

So I believe from what you've said that PetTracker would correctly show P/P, H/S, H/B once levelled to level 2.

So this just leaves your addon showing ??? for the H/B pet, and P/S for the H/S pet.

All the screenshots are from when I was using Battle Pet Breed ID as the Breed Source.

**Comment by MMOSimca** [comment]
BPBID is correct here. Pet 1 is P/P. Pet 2 is P/S. Pet 3 is either H/B or H/S, indeterminable until level 2, hence the "???". I toyed for a while with displaying "H/B or H/S" (for example) instead of "???", but there ended up being a few cases with a 4-breed stat overlap if the pet was eligible for all or almost all of the 12 breeds. That ended up making the text way too long ("H/S or H/B or P/B or S/B").

I'm not sure why PetTracker is showing H/B for the P/S pet - my guess is that there's a rounding error that happens, even if Battle Pet Breed ID is used as the data source. Just because Battle Pet Breed ID is used as the pet breed data source does not mean it is used for the calculations (probably?). I think they might be using flooring instead of rounding (I actually use flooring as well but I add 0.5 first).

I suspect if you level those 3 pets to level 2, PetTracker will suddenly identify them as P/P, P/S, and either H/B or H/S.
